//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// BkZOO.rc で使用
//
#define IDD_CHECK_BECKY_UPDATE_FORMVIEW 101
#define IDD_DETECT_NEW_BECKY_VERSION_DLG 104
#define IDR_MAINFRAME                   138
#define IDD_SETTING_DLG                 139
#define IDD_SEARCH_SITE_FORMVIEW        140
#define IDC_LIST_VIEW                   1000
#define IDC_EDIT_SHORTCUT               1001
#define IDC_BUTTON_UP                   1003
#define IDC_BUTTON_DOWN                 1004
#define IDC_BUTTON_COPY                 1005
#define IDC_BUTTON_DELETE               1006
#define IDC_BUTTON_NEW                  1007
#define IDC_EDIT_TITLE                  1008
#define IDC_EDIT_URL                    1009
#define IDC_EDIT_DEFAULT_URL            1010
#define IDC_EDIT_STATUSBAR              1011
#define IDC_COMBO_ENCODE                1012
#define IDC_COMBO_DEFAULT_ENCODE        1013
#define IDC_EDIT_DEFAULT_STATUSBAR      1014
#define IDC_COMBO_METHOD                1015
#define IDC_EDIT_REGEX                  1016
#define IDC_CHECK_TRIPLE_CLICK          1017
#define IDC_CHECK_TRIPLE_CLICK_SERVER   1017
#define IDC_CHECK_CTRL_DOUBLE_CLICK     1018
#define IDC_CHECK_TRIPLE_CLICK_SEARCH   1019
#define IDC_CHECK_CLICKABLE             1022
#define IDC_EDIT_DEFAULT_TITLE          1023
#define IDC_EDIT_DEFAULT_SHORTCUT       1024
#define IDC_CHECK2                      1026
#define IDC_CHECK_DEFAULT_SITE          1026
#define IDC_MAIN_TAB                    1027
#define IDC_STATIC_Regex_Error          1028
#define IDC_CHECK_WARNING_OPEN_URL      1029
#define IDC_EDIT_DEFAULT_SEARCH_SITE    1030
#define IDC_SYSLINK_BECKY_DOWNLOAD      1031
#define IDC_CHECK_BECKY_UPDATE          1032
#define IDC_STATIC_DETECT_NEW_BECKY_VERSION 1033
#define IDC_CHECK_CHECK_BECKY_UPDATE_DISABLE 1034
#define IDC_GROUP_BOX_CHECK_BECKY_UPDATE 1035
#define IDC_STATIC_DESCRIPTION          1036
#define IDC_SYSLINK_BKZOO_HOME          1037
#define IDC_CHECK_CTRL_TRIPLE_CLICK     1038
#define IDS_STRING_MENU_STATUS_BROWZER  40000
#define IDS_STRING_WARNING_MESSAGE_REGEX 40001
#define IDS_STRING_MENU_STATUS_EXPLORER 40002
#define IDS_STRING_MENU_STATUS_SVN      40003
#define IDS_STRING_MENU_STATUS_PASTE_FILE_KEYWORD 40004
#define IDS_STRING_GOOGLE_SEARCH_PARAMS 40006
#define IDS_STRING_ERR_MESSAGE_NO_SELECTED_STR 40007
#define IDS_STRING_ERR_MESSAGE_NO_CLIPBOARD_STR 40008
#define IDS_STRING_ERR_MESSAGE_STATUS_INVALID_URL_AND_TRUNCATED 40009
#define IDS_STRING_MENU_STATUS_GOOGLE_SEARCH 40010
#define IDS_STRING_MENU_STATUS_FFFTP    40011
#define IDS_STRING_MENU_STATUS_FILEZILLA 40012
#define IDS_STRING_MENU_STATUS_WINSCP   40013
#define IDS_STRING_ERR_MESSAGE_STATUS_INVALID_URL 40014
#define IDS_STRING_MENU_STATUS_TERATERM 40015
#define IDS_STRING_MENU_STATUS_REMOTE_DESKTOP 40016
#define IDS_STRING_ERR_MESSAGE_SHELL_EXECUTE 40017
#define IDS_STRING_ERR_MESSAGE_TRUNCATED_FILE_URI 40018
#define IDS_STRING_ERR_MESSAGE_NO_SITE_URL 40019
#define IDS_STRING_ERR_MESSAGE_WARNING_OPEN_URL 40020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
